services:
  phpbe-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: phpbe
    container_name: phpbe_app_service
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - Jwt__Secret=${JWT_SECRET}
    networks:
      - dapr-network

  phpbe-daprd:
    image: "daprio/daprd:latest"
    container_name: phpbe_daprd_sidecar
    command: [
      "./daprd",
      "--app-id", "myapp",
      "--app-port", "5000",
      "--app-protocol", "http",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--components-path", "/components",
      "--log-level", "debug"
    ]
    volumes:
      - "./components/stage:/components"
    depends_on:
      - phpbe-app
      - redis
    network_mode: "service:phpbe-app"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: dapr_redis_for_phpbe_with_pass
    ports:
      - "6380:6379"
   command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
