apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 192.168.100.14:16379
  - name: redisPassword
    value: "ThInK4!*!!"